name: scrnaseq
channels:
  - pyg
  - https://mirrors.pku.edu.cn/anaconda/cloud/bioconda
  - nvidia
  - pytorch
  - https://mirrors.pku.edu.cn/anaconda/pkgs/main
  - https://mirrors.pku.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.pku.edu.cn/anaconda/pkgs/main/
  - https://mirrors.pku.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.pku.edu.cn/anaconda/cloud/bioconda/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=py311h06a4308_0
  - adjusttext=1.2.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.0=py311h06a4308_0
  - aiohttp=3.10.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anndata=0.10.9=pyhd8ed1ab_0
  - annotated-types=0.6.0=py311h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arpack=3.8.0=nompi_h0baa96a_101
  - array-api-compat=1.9=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=ha770c72_10_cpu
  - ase=3.23.0=pyhd8ed1ab_0
  - astor=0.8.1=py311h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - autograd=1.5=py311h06a4308_0
  - autograd-gamma=0.5.0=py311h06a4308_0
  - aws-c-auth=0.6.25=haec726b_4
  - aws-c-cal=0.5.21=hb6b25a1_1
  - aws-c-common=0.8.12=h0b41bf4_0
  - aws-c-compression=0.2.16=hea85486_4
  - aws-c-event-stream=0.2.20=hddb6542_2
  - aws-c-http=0.7.5=hdfd1699_3
  - aws-c-io=0.13.18=hf4b7f4e_3
  - aws-c-mqtt=0.8.6=hfdaba90_9
  - aws-c-s3=0.2.6=hf4c50b5_0
  - aws-c-sdkutils=0.1.7=hea85486_4
  - aws-checksums=0.1.14=hea85486_4
  - aws-crt-cpp=0.19.8=hd2d6fe4_7
  - aws-sdk-cpp=1.10.57=hd18c533_7
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - bioservices=1.11.2=pyhd8ed1ab_1
  - blas=1.0=mkl
  - blinker=1.6.2=py311h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - boltons=23.0.0=py311h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - captum=0.7.0=py311h06a4308_0
  - certifi=2024.8.30=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_0
  - cfitsio=3.470=h5893167_7
  - chardet=4.0.0=py311h06a4308_1003
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - chex=0.1.5=py311h06a4308_0
  - click=8.1.7=py311h06a4308_0
  - cloudpickle=3.0.0=py311h06a4308_0
  - colorama=0.4.6=py311h06a4308_0
  - colorcet=3.1.0=py311h06a4308_0
  - coloredlogs=15.0.1=py311h06a4308_2
  - colorlog=5.0.1=py311h06a4308_1
  - colormath=3.0.0=py_2
  - contextlib2=21.6.0=py311h06a4308_0
  - cpuonly=2.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - cutadapt=4.9=py311hdad781d_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - datasets=2.2.1=pyhd8ed1ab_0
  - datashader=0.16.3=py311h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.8=py311h06a4308_0
  - dm-tree=0.1.7=py311h6a678d5_1
  - dnaio=1.2.1=py311hdad781d_2
  - docrep=0.3.2=pyh44b312d_0
  - easydev=0.12.0=pyh6c4a22f_0
  - einops=0.8.0=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py311h06a4308_0
  - exceptiongroup=1.2.0=py311h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - fastqc=0.12.1=hdfd78af_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - flask=3.0.3=py311h06a4308_0
  - flax=0.6.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - formulaic=0.6.2=py311h06a4308_1
  - freetype=2.12.1=h4a9f257_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - fsspec=2024.6.1=py311h06a4308_0
  - future=0.18.3=py311h06a4308_0
  - gdbm=1.18=hd4cb3f1_4
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gdown=5.2.0=pyhd8ed1ab_0
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gevent=23.9.1=py311h5eee18b_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.6.0=h6f12383_0
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.78.1=py311h42194e9_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - greenlet=3.0.1=py311h6a678d5_0
  - grequests=0.6.0=pyh9f0ad1d_0
  - grpcio=1.52.1=py311hcafe171_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.12.1=h2b7332f_3
  - hnswlib=0.7.0=py311h92ebd52_2
  - huggingface_hub=0.24.6=py311h06a4308_0
  - humanfriendly=10.0=py311h06a4308_1
  - humanize=3.10.0=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - imagecodecs=2023.1.23=py311h8105a5c_0
  - imageio=2.33.1=py311h06a4308_0
  - importlib-metadata=7.0.1=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - interface_meta=1.3.0=py311h06a4308_0
  - ipywidgets=8.1.2=py311h06a4308_0
  - isa-l=2.31.0=h4bc722e_2
  - isodate=0.6.1=py311h06a4308_0
  - itsdangerous=2.2.0=py311h06a4308_0
  - jax=0.4.7=pyhd8ed1ab_0
  - jaxlib=0.4.6=cpu_py311h9f877bd_1
  - jaxopt=0.8.3=pyhd8ed1ab_0
  - jedi=0.19.1=py311h06a4308_0
  - jinja2=3.1.4=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyterlab_widgets=3.0.10=py311h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - kaleido-core=0.2.1=h7c8854e_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - lerc=3.0=h295c915_0
  - libabseil=20230125.0=cxx17_hcb278e6_1
  - libaec=1.0.4=he6710b0_1
  - libarrow=11.0.0=h5ab077d_10_cpu
  - libavif=0.11.1=h5eee18b_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=h109eef0_2
  - libboost-python=1.82.0=py311h92ebd52_6
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_1
  - libgoogle-cloud=2.8.0=h0bc5f78_1
  - libgrpc=1.52.1=hcf146ea_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.21.12=hfc55251_2
  - librsvg=2.54.4=haac4a5d_4
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.18.0=h5e4af38_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.1=hfdd30dd_2
  - libxslt=1.1.41=h097e994_0
  - libzlib=1.2.13=h4ab18f5_6
  - libzopfli=1.0.3=he6710b0_0
  - lifelines=0.29.0=pyhd8ed1ab_0
  - lightning=2.4.0=pyhd8ed1ab_0
  - lightning-utilities=0.11.7=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py311h6a678d5_0
  - locket=1.0.0=py311h06a4308_0
  - lxml=5.2.1=py311h57af460_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py311h06a4308_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - mathjax=2.7.5=h06a4308_0
  - matplotlib-base=3.6.2=py311h945d387_0
  - mdurl=0.1.0=py311h06a4308_0
  - mellon=1.4.3=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.10=py311h5eee18b_0
  - mkl_random=1.2.7=py311ha02d727_0
  - ml-collections=0.1.1=pyhd8ed1ab_0
  - ml_dtypes=0.4.0=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - mudata=0.3.1=pyhd8ed1ab_0
  - multidict=6.0.4=py311h5eee18b_0
  - multipledispatch=0.6.0=py311h06a4308_0
  - multiprocess=0.70.15=py311h06a4308_0
  - multiqc=1.25=pyhdfd78af_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.60.0=py311h4bc866e_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - numpyro=0.13.2=pyhd8ed1ab_0
  - omicverse=1.6.7=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjdk=11.0.13=h87a67e3_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py311h5eee18b_0
  - openssl=3.0.15=h5eee18b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optax=0.1.4=py311h06a4308_0
  - orc=1.8.2=hfdbbad2_2
  - packaging=24.1=py311h06a4308_0
  - pango=1.50.7=h05da053_0
  - param=2.1.1=py311h06a4308_0
  - partd=1.4.1=py311h06a4308_0
  - patsy=0.5.6=py311h06a4308_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.42=hebb0a14_1
  - perl=5.34.0=h5eee18b_2
  - pgmpy=0.1.24=py311h38be061_1
  - pigz=2.6=h27cfd23_0
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - plotly=5.24.1=py311h92b7b1e_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - progressbar2=4.2.0=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.21.12=py311hcafe171_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyaml-env=1.2.1=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycairo=1.23.0=py311hd1222b9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py311h06a4308_0
  - pydantic=2.8.2=py311h06a4308_0
  - pydantic-core=2.20.1=py311hb02cf49_0
  - pyg=2.5.2=py311_torch_2.2.0_cpu
  - pygam=0.9.1=pyhd8ed1ab_0
  - pygments=2.15.1=py311h06a4308_1
  - pynvml=11.5.3=pyhd8ed1ab_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-igraph=0.11.2=py311h535dc8a_1
  - python-isal=1.7.1=py311h9ecbd09_0
  - python-kaleido=0.2.1=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-utils=3.3.3=py311h06a4308_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python-zlib-ng=0.5.1=py311h1a83624_0
  - python_abi=3.11=2_cp311
  - pytorch=2.2.2=py3.11_cpu_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.3.0=py311h06a4308_0
  - pytorch-mutex=1.0=cpu
  - pytorch_geometric=2.6.1=pyhe5570ce_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - rdflib=7.0.0=pyhd8ed1ab_0
  - rdkit=2023.03.3=py311h4c2f14b_1
  - re2=2023.02.02=hcb278e6_0
  - readline=8.2=h5eee18b_0
  - regex=2024.9.11=py311h5eee18b_0
  - reportlab=4.2.5=py311h9ecbd09_0
  - requests=2.32.3=py311h06a4308_0
  - requests_cache=0.4.13=py_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rich=13.7.1=py311h06a4308_0
  - rich-click=1.8.3=pyhd8ed1ab_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - s2n=1.3.38=h3358134_0
  - safetensors=0.4.5=py311h9e33e62_0
  - scanpy=1.10.3=pyhd8ed1ab_0
  - scikit-image=0.24.0=py311ha02d727_0
  - scikit-misc=0.1.4=py311ha9cf758_4
  - scvi-tools=1.2.0=pyhd8ed1ab_0
  - seaborn=0.13.2=py311h06a4308_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.1.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sparse=0.15.4=pyh267e887_1
  - spectra=0.0.11=py_1
  - sqlalchemy=2.0.34=py311h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stdlib-list=0.10.0=py311h06a4308_0
  - suds-community=1.1.2=pyhd8ed1ab_0
  - sympy=1.13.2=py311h06a4308_0
  - tabulate=0.9.0=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.3=py311h06a4308_0
  - tensorboard=2.17.0=py311h06a4308_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_1
  - termcolor=2.1.0=py311h06a4308_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tifffile=2023.4.12=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.19.1=py311h585d796_0
  - toolz=0.12.0=py311h06a4308_0
  - torchaudio=2.2.2=py311_cpu
  - torchmetrics=1.4.0.post0=py311h06a4308_0
  - torchtriton=3.0.0=py311
  - torchvision=0.15.2=cuda118py311h4cc2eb7_0
  - tqdm=4.66.5=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - transformers=4.44.1=py311h06a4308_0
  - trim-galore=0.6.10=hdfd78af_0
  - trimesh=4.4.9=pyhd8ed1ab_0
  - typeguard=4.2.1=py311h06a4308_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - urllib3=2.2.3=py311h06a4308_0
  - werkzeug=3.0.3=py311h06a4308_0
  - wheel=0.44.0=py311h06a4308_0
  - widgetsnbextension=4.0.10=py311h06a4308_0
  - wrapt=1.14.1=py311h5eee18b_0
  - xarray=2023.6.0=py311h06a4308_0
  - xmltodict=0.13.0=py311h06a4308_0
  - xopen=2.0.2=pyh707e725_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py311h5eee18b_0
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.17.0=py311h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zlib-ng=2.2.2=h5888daf_0
  - zope=1.0=py311h06a4308_1
  - zope.event=5.0=py311h06a4308_0
  - zope.interface=5.4.0=py311h5eee18b_0
  - zstandard=0.22.0=py311h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - annoy==1.17.3
      - anyio==4.6.0
      - arboreto==0.1.6
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - bcrypt==4.2.0
      - bleach==6.1.0
      - bokeh==3.6.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cosg==1.0.1
      - cryptography==43.0.1
      - ctxcore==0.2.0
      - cycler==0.12.1
      - cython==3.0.11
      - cytoolz==1.0.0
      - dask==2024.9.1
      - dask-expr==1.1.15
      - debugpy==1.8.6
      - decoupler==1.8.0
      - defusedxml==0.7.1
      - distributed==2024.9.1
      - executing==2.1.0
      - face==20.1.1
      - fastjsonschema==2.20.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozendict==2.4.4
      - glom==23.5.0
      - h11==0.14.0
      - h5py==3.12.1
      - harmonypy==0.0.10
      - httpcore==1.0.6
      - httpx==0.27.2
      - igraph==0.11.6
      - inflect==7.4.0
      - interlap==0.2.7
      - ipykernel==6.29.5
      - ipython==8.28.0
      - isoduration==20.11.0
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - legendkit==0.3.4
      - leidenalg==0.10.2
      - loompy==3.0.7
      - louvain==0.8.2
      - lz4==4.3.3
      - marsilea==0.4.6
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - more-itertools==10.5.0
      - multiprocessing-on-dill==3.5.0a4
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy-groupies==0.11.2
      - omnipath==1.0.8
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - paramiko==3.5.0
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - psutil==6.0.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pybiomart==0.2.0
      - pycurl==7.45.3
      - pydeseq2==0.4.11
      - pynacl==1.5.0
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pypath-common==0.2.5
      - pypath-omnipath==0.16.17
      - pyreadr==0.5.2
      - pyscenic==0.12.1
      - pysftp==0.2.9
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyzmq==26.2.0
      - rdata==0.11.2
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - scrublet==0.2.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlparse==0.5.1
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - tblib==3.0.0
      - terminado==0.18.1
      - texttable==1.7.0
      - timeloop==1.0.2
      - tinycss2==1.3.0
      - toml==0.10.2
      - tornado==6.4.1
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xlrd==2.0.1
      - xyzservices==2024.9.0
      - zict==3.0.0
prefix: /home/shuaifeng_wang/anaconda3/envs/scrnaseq
